ARG GO_VERSION=1.25
FROM golang:${GO_VERSION}-bookworm AS builder

WORKDIR /src

COPY ./ ./

WORKDIR /src/internal/examples

ENV GOPROXY="https://proxy.golang.org,direct"

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w" -o server/bin/server server/main.go

FROM gcr.io/distroless/static-debian12:nonroot@sha256:afa5c872c891853ca7fcf1f12c3edb23f7eeef36189728842dd51042ff57f7ab

WORKDIR /app

COPY --from=builder /src/internal/examples/server/bin/server ./

EXPOSE 4320 4321

ENTRYPOINT ["./server"]
