name: govuln 

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  govulncheck:
    name: govulncheck (project)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.22"
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.22
           go-package: ./...
