name: govulncheck

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    tags:
      - 'v*'
    branches:
      - main

permissions:
  contents: read

jobs:
  govulncheck:
    name: govulncheck (project)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1.1.0
        with:
          repo-checkout: false
          go-version-file: "go.mod"
          cache: false
          go-package: ./...
