name: static-check

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  lint:
    name: lint project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - id: install_go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6 
