name: static-check

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    tags:
      - 'v*'
    branches:
      - main

permissions:
  contents: read

jobs:
  staticcheck:
    name: staticcheck (project)
    strategy:
      matrix:
        dir: ["client", "internal", "server", "protobufshelpers"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 1
      - id: install_go
        uses: WillAbides/setup-go-faster@fea1b51f8e1f07229131e4438f235ad219880d31 # v1.19.0
        with:
          go-version-file: "go.mod"
      - uses: dominikh/staticcheck-action@9716614d4101e79b4340dd97b10e54d68234e431 # v1.4.1
        with:
          install-go: false
          version: "2025.1.1"
          working-directory: ${{ matrix.dir }}
